# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhuotMaps' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PhuotMaps
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.5.1'

  

  platform :ios, '9.0'
  target 'PhuotMapsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PhuotMaps-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PhuotMaps-tvOS

  target 'PhuotMaps-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
